mdapipkg/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Icon_URL__c</fullName>
        <label>Icon URL</label>
        <type>Url</type>
    </fields>
</CustomObject>

mdapipkg/objects/Quotation_Iteration__c.object
<CustomObject>
    <fields>
        <fullName>Bid_Price__c</fullName>
        <label>Bid Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Bid_Volume__c</fullName>
        <label>Bid Volume</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Buyer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Buyer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Quotation_Iterations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Consumer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Consumer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotation Iterations</relationshipLabel>
        <relationshipName>Quotation_Iterations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Quotation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Quotation</label>
        <referenceTo>Quotation__c</referenceTo>
        <relationshipLabel>Quotation Iterations</relationshipLabel>
        <relationshipName>Quotation_Iterations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Producer__c</fullName>
        <label>Producer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotation Iterations (Producer)</relationshipLabel>
        <relationshipName>Quotation_Iterations1</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quotation_Status__c</fullName>
        <label>Quotation Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Pulled</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Counter</fullName>
                </value>
                <value>
                    <fullName>Left</fullName>
                </value>
                <value>
                    <fullName>Done Deal</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Seller__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Seller</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Quotation_Iterations1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quotation Iteration</label>
    <nameField>
        <label>Quotation Iteration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotation Iterations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/NotificationController.cls
public class NotificationController {

	@AuraEnabled
	public static Map<String,Object> getNotify()
	{
		Account myAccount = UserService.getAccount();
		String findConsumer = myAccount == null?'': ' AND Producer__c =\''+myAccount.Id+'\' ';
		Map<String,Object> res = new Map<String,Object>();	
		String soql = 'SELECT Id,'+
		'Name,'+
		'Bid_Price__c,'+
		'Bid_Volume__c,'+
		//'Consumer__r.Icon_URL__c,'+
		//'Consumer__r.Name,'+
		//'Buyer__r.Name,'+
		//'Buyer__c,'+

		//'Producer__r.Icon_URL__c,'+
		//'Producer__r.Name,'+
		//'Seller__r.Name,'+
		//'Seller__c,'+

		'CreatedBy.Contact.Account.Icon_URL__c,'+
		'CreatedBy.Id,'+
		'CreatedBy.Name,'+
		'Quotation_Status__c,'+
		'Primary_Quotation__c,'+
		'CreatedDate FROM Quotation_Iteration__c '+
		'WHERE Bid_Price__c != NULL '+
		findConsumer +
		'ORDER BY CreatedDate DESC LIMIT 10';
		System.debug('soql : '+soql);
		List<Quotation_Iteration__c> listAccount = Database.query(soql);
		res.put('list',listAccount);

		return res;
	}
}