mdapipkg/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Consumer</fullName>
        <active>true</active>
        <label>Consumer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Producer</fullName>
        <active>true</active>
        <label>Producer</label>
    </recordTypes>
</CustomObject>

mdapipkg/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Natural Rubber</fullName>
                </value>
                <value>
                    <fullName>Synthetic</fullName>
                </value>
                <value>
                    <fullName>Latex</fullName>
                </value>
                <value>
                    <fullName>Non-Rubber</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

mdapipkg/objects/Factory__c.object
<CustomObject>
    <fields>
        <fullName>Factory_Location__c</fullName>
        <label>Factory Location</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Africa</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Cambodia</fullName>
                </value>
                <value>
                    <fullName>Cameroon</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Coast</fullName>
                </value>
                <value>
                    <fullName>Congo</fullName>
                </value>
                <value>
                    <fullName>Cote D-lvoire</fullName>
                </value>
                <value>
                    <fullName>D-Lvoire</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Guatemala</fullName>
                </value>
                <value>
                    <fullName>Indonesia</fullName>
                </value>
                <value>
                    <fullName>Ivory Coast</fullName>
                </value>
                <value>
                    <fullName>Kingdom</fullName>
                </value>
                <value>
                    <fullName>Malaysia</fullName>
                </value>
                <value>
                    <fullName>Myanmar</fullName>
                </value>
                <value>
                    <fullName>Nigeria</fullName>
                </value>
                <value>
                    <fullName>Philipines</fullName>
                </value>
                <value>
                    <fullName>Phillippines</fullName>
                </value>
                <value>
                    <fullName>Singapore</fullName>
                </value>
                <value>
                    <fullName>Sri-Lanka</fullName>
                </value>
                <value>
                    <fullName>Switzerland</fullName>
                </value>
                <value>
                    <fullName>Thailand</fullName>
                </value>
                <value>
                    <fullName>U.S.A.</fullName>
                </value>
                <value>
                    <fullName>United Kingdom</fullName>
                </value>
                <value>
                    <fullName>Vietnam</fullName>
                </value>
                <value>
                    <fullName>TBC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Factory</label>
    <nameField>
        <label>Factory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Factories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapipkg/objects/Payment_Term__c.object
<CustomObject>
    <fields>
        <fullName>Consumer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Consumer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payment Terms</relationshipLabel>
        <relationshipName>Payment_Terms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Factory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Factory</label>
        <referenceTo>Factory__c</referenceTo>
        <relationshipLabel>Payment Terms</relationshipLabel>
        <relationshipName>Payment_Terms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Term__c</fullName>
        <label>Payment Term</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Payable immediately Due net</fullName>
                </value>
                <value>
                    <fullName>14 days from invoice date</fullName>
                </value>
                <value>
                    <fullName>30 Days After Invoice</fullName>
                </value>
                <value>
                    <fullName>TT 5 Days After End Of Month</fullName>
                </value>
                <value>
                    <fullName>100 Days From BL Date</fullName>
                </value>
                <value>
                    <fullName>120 Days From BL Date</fullName>
                </value>
                <value>
                    <fullName>123 Days from  BL Date</fullName>
                </value>
                <value>
                    <fullName>120 Day BL Date via DB RF Line</fullName>
                </value>
                <value>
                    <fullName>150 Days From BL Date</fullName>
                </value>
                <value>
                    <fullName>30 Days from Presentation Date</fullName>
                </value>
                <value>
                    <fullName>30 Days from Date We Present Documents</fullName>
                </value>
                <value>
                    <fullName>30 Days Prepayment before Shipment</fullName>
                </value>
                <value>
                    <fullName>TT 45 Days After End Of Month</fullName>
                </value>
                <value>
                    <fullName>TT 60 Days After End Of Month</fullName>
                </value>
                <value>
                    <fullName>90 Days EOM upon Shipment</fullName>
                </value>
                <value>
                    <fullName>120 Days Aft Arrival Of Vessel</fullName>
                </value>
                <value>
                    <fullName>30 Days After Arrival</fullName>
                </value>
                <value>
                    <fullName>30% against documents, Balance on Arrival</fullName>
                </value>
                <value>
                    <fullName>30% Against presentation of Orig Doc; Bal on Arriv</fullName>
                </value>
                <value>
                    <fullName>50% in Advance; Bal 50% against faxed documents</fullName>
                </value>
                <value>
                    <fullName>100% Prepayment 1 Week before Shipment</fullName>
                </value>
                <value>
                    <fullName>70% in Advance Against Faxed Copy Doc,30% Aft GR</fullName>
                </value>
                <value>
                    <fullName>100% Pre-payment prompt after contract date</fullName>
                </value>
                <value>
                    <fullName>Not applicable</fullName>
                </value>
                <value>
                    <fullName>55% Faxed Copy and Balance is Aftr DRC Determ.</fullName>
                </value>
                <value>
                    <fullName>Setoff settlement against ....</fullName>
                </value>
                <value>
                    <fullName>Advance Payment  (TT in Advance)</fullName>
                </value>
                <value>
                    <fullName>50% Upon Faxed Copy of BL</fullName>
                </value>
                <value>
                    <fullName>TT faxed copy of shipping doc(7 days from BL Date)</fullName>
                </value>
                <value>
                    <fullName>30 days from BL Date</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Payment Term</label>
    <nameField>
        <displayFormat>P-{0000000}</displayFormat>
        <label>Payment Term Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapipkg/objects/Quotation__c.object
<CustomObject>
    <fields>
        <fullName>All_or_Nothing__c</fullName>
        <defaultValue>true</defaultValue>
        <label>All or Nothing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Bid_Price__c</fullName>
        <label>Bid Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Bid_Volume__c</fullName>
        <label>Bid Volume</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Buyer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Buyer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Quotation1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Consumer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Consumer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Consumer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotation (Consumer)</relationshipLabel>
        <relationshipName>Quotation_C</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Factory__c</fullName>
        <label>Factory</label>
        <referenceTo>Factory__c</referenceTo>
        <relationshipLabel>Quotation</relationshipLabel>
        <relationshipName>Quotation</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Grade__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Grade</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Quotation</relationshipLabel>
        <relationshipName>Quotation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Packing__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Packing</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Quotation (Packing)</relationshipLabel>
        <relationshipName>Quotation1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Term__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment Term</label>
        <referenceTo>Payment_Term__c</referenceTo>
        <relationshipLabel>Quotation</relationshipLabel>
        <relationshipName>Quotation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Producer__c</fullName>
        <label>Producer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Producer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotation</relationshipLabel>
        <relationshipName>Quotation</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quote_Effective_Month__c</fullName>
        <label>Quote Effective Month</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Shipment_Information__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shipment Information</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipLabel>Quotation</relationshipLabel>
        <relationshipName>Quotation</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quotation</label>
    <nameField>
        <displayFormat>Q-{0000000}</displayFormat>
        <label>Quotation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapipkg/classes/Test_OfferPanelController.cls
@isTest
private class Test_OfferPanelController {

	static Map<String,Object> mockupProducerData() {
		
		RecordType producerRecordType = [Select Id,name From RecordType where sobjecttype = 'Account' and Name = 'Producer'];
		RecordType consumerRecordType = [Select Id,name From RecordType where sobjecttype = 'Account' and Name = 'Consumer'];

		User userLogin =  UserService.getUser();

		Account producer = new Account();
		producer.Name = 'Halcyon';
		producer.RecordTypeId = producerRecordType.Id;
		insert producer;

		Account consumer = new Account();
		consumer.Name = 'Consumer1';
		consumer.RecordTypeId = consumerRecordType.Id;
		insert consumer;

		Contact myContact = new Contact();
		myContact.LastName = 'Helcyon User1';
		myContact.AccountId = producer.Id;
		myContact.ownerid = UserInfo.getUserId();
		insert myContact;

		userLogin.Contact = myContact;
		update userLogin;


		Factory__c factory = new Factory__c();
		factory.Name = 'Factory 1';
		factory.Factory_Location__c = 'Thailand';
		insert factory;


		User Buyer = [SELECT Id FROM User WHERE Username = 'consumer1@heveaconnect.test'];
		Date dateQuote = Helper.get1stDateNow();
    	Quotation__c quoteObj = new Quotation__c();
    	quoteObj.Buyer__c = Buyer.Id;
        quoteObj.Consumer__c = consumer.Id;
        //quoteObj.Grade__c = filterGrades.Product__r.Id;
        //quoteObj.Packing__c = filterPacking.Product__r.Id;
        //quoteObj.Payment_Term__c = filterPaymentTerms.Id;
        //quoteObj.Shipment_Information__c = filterShipmentInformation.Id;
        quoteObj.Factory__c = factory.Id;

        quoteObj.Bid_Price__c = 1000;
        quoteObj.Bid_Volume__c = 100.8;
        quoteObj.Month__c = Helper.getMonthStr(dateQuote.month());
        quoteObj.Quote_Effective_Month__c = dateQuote;
        quoteObj.All_or_Nothing__c = false;
        quoteObj.Producer__c = producer.Id;
        insert quoteObj;
		
		return new Map<String,Object>
		{
			'quoteObj'=>quoteObj
		};		
	}
	
	@isTest static void test_getFilterInfo() {
		Test.StartTest();
		Account myAccount = UserService.getAccount();
		Map<String,Object>  result =  OfferPanelController.getFilterInfo();
		Test.StopTest();
	}
	
	@isTest static void test_getInformation() {
		Test.StartTest();
		Map<String,Object> result =  OfferPanelController.getInformation(new Map<String,String>{
			'consumer'=>'All',
			'country'=>'Indonesia',
			'date'=>'2019-01-01'
		});
		Test.StopTest();
	}
		@isTest static void test_getOfferList() {
		Test.StartTest();
		Map<String,Object> result =  OfferPanelController.getOfferList(new Map<String,String>{
			'consumer'=>'All',
			'country'=>'Indonesia',
			'date'=>'2019-01-01'
		});
		Test.StopTest();
	}

	@isTest static void test_getQuoteFormat() {
		Test.StartTest();
		Account myAccount = UserService.getAccount();
		Map<String,Object> result =  OfferPanelController.getQuoteFormat('All','Indonesia',Date.valueOf('2019-01-01'));
		Test.StopTest();
	}
	
}