mdapipkg/objects/Quotation__c.object
<CustomObject>
    <fields>
        <fullName>Quotation_Status__c</fullName>
        <label>Quotation Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Pulled</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Counter</fullName>
                </value>
                <value>
                    <fullName>Left</fullName>
                </value>
                <value>
                    <fullName>Done Deal</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quotation</label>
    <nameField>
        <displayFormat>Q-{0000000}</displayFormat>
        <label>Quotation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/cleanQuoteByStatus.cls
public with sharing class cleanQuoteByStatus {
	List<Quotation__c> quoteList {set;get;}
	List<Quotation__c> quoteListUpdate {set;get;}
	public cleanQuoteByStatus(List<sObject> scope)
 	{
 		this.quoteList = new List<Quotation__c>();
        for(sObject s : scope){
        	this.quoteList.add((Quotation__c)s);
        }	
 	}

 	public void cleanQuote()
 	{
 		this.quoteListUpdate = new List<Quotation__c>();
 		for(Quotation__c quoteModel :this.quoteList)
 		{
 			quoteModel.Quotation_Status__c = 'Cancelled';
 			this.quoteListUpdate.add(quoteModel);
 		}

 	}

 	public void updateQuote()
 	{
 		upsert this.quoteListUpdate;
 	}
}