mdapipkg/objects/Quotation__c.object
<CustomObject>
    <fields>
        <fullName>Quotation_Status__c</fullName>
        <label>Quotation Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Pulled</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Counter</fullName>
                </value>
                <value>
                    <fullName>Left</fullName>
                </value>
                <value>
                    <fullName>Done Deal</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quotation</label>
    <nameField>
        <displayFormat>Q-{0000000}</displayFormat>
        <label>Quotation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/Batch_cleanQuoteByStatus.cls
global class Batch_cleanQuoteByStatus implements Database.Batchable<sObject> {
	
	String query;
	
	global Batch_cleanQuoteByStatus() {
		
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC) {
		Datetime now = Datetime.now();
		query = 'SELECT Id,Quotation_Status__c FROM Quotation__c WHERE Quotation_Status__c in (\'Rejected\',\'Done Deal\') AND LastModifiedDate < '+now.addDays(-1).formatGMT('yyyy-MM-dd\'T\'HH:mm:ss\'Z\'');
		return Database.getQueryLocator(query);
	}

   	global void execute(Database.BatchableContext BC, List<sObject> scope) {
		cleanQuoteByStatus Cal = new cleanQuoteByStatus(scope);
		Cal.cleanQuote();
		Cal.updateQuote();
	}
	
	global void finish(Database.BatchableContext BC) {
		
	}
	
}